### ISSUE TITLE
Use Kiota info command to install required dependencies

### ISSUE THREAD

**Issue by kfcampbell** [octokit/source-generator#17]
The Kiota CLI offers an [info command](https://learn.microsoft.com/en-us/openapi/kiota/using#language-information) that prints the dependencies required to work with a project. source-generator currently [installs a fixed set of dependencies](https://github.com/octokit/source-generator/blob/09f2c9794b24e2a28018c87cb2c19ed94b5697b3/post-processors/go/main.go#L67-L74) that were discovered through trial and error.

The info command will keep up with future changes to dependencies, so we should parse the output of that to install required packages instead of going the hard-coded route.

**Comment by baywet** [comment]
FYI thanks to @andreaTP 's work, this command now supports a --json to output the result as JSON and for machine processing.
